version: "3.8"

services:
  static:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    restart: always
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
    env_file:
      - .env
    ports:
      - ${API_SERVER_PORT}:8000
    command: [
        "poetry", "run", "uvicorn", "app:create_app",
        "--host", "0.0.0.0",
        "--port", '8000'
    ]